#!/usr/bin/env python3
"""Build curriculum/vocab-index.md from the vocab book's PDF outline.

Re-runnable. Reads materials/vocab-book.pdf, walks its bookmark outline, keeps the
448 numbered units (titles like "182 漫漫求职路"), records each unit's chapter and
1-indexed page range, and writes a committable markdown table.

The index is the "menu" the /vocab and /lesson skills use to pick a themed unit by
week, without ever re-parsing the 1,633-page PDF.
"""
import os
import re
import sys

from pypdf import PdfReader

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PDF = os.path.join(ROOT, "materials", "vocab-book.pdf")
OUT = os.path.join(ROOT, "curriculum", "vocab-index.md")

UNIT_RE = re.compile(r"^\d+\s")
CHAPTER_RE = re.compile(r"^Chapter\s*\d+", re.IGNORECASE)


def main():
    if not os.path.exists(PDF):
        sys.exit(f"PDF not found at {PDF} — copy the vocab book there first.")

    reader = PdfReader(PDF)
    total_pages = len(reader.pages)

    # Flatten the outline in reading order, tagging chapter context as we go.
    units = []  # (unit_no, title, chapter, start_page)
    current_chapter = ""

    def page_of(item):
        try:
            return reader.get_destination_page_number(item) + 1  # 1-indexed
        except Exception:
            return None

    def walk(outline):
        nonlocal current_chapter
        for item in outline:
            if isinstance(item, list):
                walk(item)
                continue
            title = str(item.title).strip()
            if CHAPTER_RE.match(title):
                current_chapter = title
            elif UNIT_RE.match(title):
                page = page_of(item)
                if page is not None:
                    num = int(title.split(None, 1)[0])
                    name = title.split(None, 1)[1] if " " in title else ""
                    units.append((num, name, current_chapter, page))

    walk(reader.outline)
    units.sort(key=lambda u: u[0])

    # End page = next unit's start - 1 (last unit runs to end of book).
    rows = []
    for i, (num, name, chapter, start) in enumerate(units):
        end = (units[i + 1][3] - 1) if i + 1 < len(units) else total_pages
        rows.append((num, name, chapter, start, end))

    lines = [
        "# Vocabulary Unit Index",
        "",
        f"Source: `materials/vocab-book.pdf` ({total_pages} pages, {len(rows)} units). "
        "Generated by `scripts/vocab_build_index.py`.",
        "Pages are 1-indexed. Use `scripts/vocab_extract.py --unit N` to pull one unit's words.",
        "",
        "| unit | title | chapter | start_page | end_page |",
        "|------|-------|---------|------------|----------|",
    ]
    for num, name, chapter, start, end in rows:
        lines.append(f"| {num} | {name} | {chapter} | {start} | {end} |")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {OUT} with {len(rows)} units.")


if __name__ == "__main__":
    main()
